import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from "@next/font/google";
import { Inter } from 'next/font/google'
import { Providers } from '../../context/redux.provider'

const monstserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-monstserrat",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${monstserrat.className} px-4 py-4 block items-center`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
